/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

/**
 *
 * @author Enrique Rodriguez
 */
public class FrmPantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPantallaPrincipal
     */
    public FrmPantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnModulodeReportes = new javax.swing.JButton();
        btnModuloLicencias = new javax.swing.JButton();
        btnModuloPlacas = new javax.swing.JButton();
        btnCambioPlacas = new javax.swing.JButton();
        btnModuloConsultas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnModulodeReportes.setContentAreaFilled(false);
        btnModulodeReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModulodeReportesActionPerformed(evt);
            }
        });
        getContentPane().add(btnModulodeReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 400, 60));

        btnModuloLicencias.setContentAreaFilled(false);
        btnModuloLicencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloLicenciasActionPerformed(evt);
            }
        });
        getContentPane().add(btnModuloLicencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 400, 50));

        btnModuloPlacas.setContentAreaFilled(false);
        btnModuloPlacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloPlacasActionPerformed(evt);
            }
        });
        getContentPane().add(btnModuloPlacas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 400, 60));

        btnCambioPlacas.setContentAreaFilled(false);
        btnCambioPlacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambioPlacasActionPerformed(evt);
            }
        });
        getContentPane().add(btnCambioPlacas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 400, 60));

        btnModuloConsultas.setContentAreaFilled(false);
        btnModuloConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloConsultasActionPerformed(evt);
            }
        });
        getContentPane().add(btnModuloConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 400, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PantallaPrincipa.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnModulodeReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModulodeReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModulodeReportesActionPerformed

    private void btnModuloLicenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloLicenciasActionPerformed
        FrmModuloLicencias on = new FrmModuloLicencias();
        on.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnModuloLicenciasActionPerformed

    private void btnModuloPlacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloPlacasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModuloPlacasActionPerformed

    private void btnCambioPlacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambioPlacasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCambioPlacasActionPerformed

    private void btnModuloConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModuloConsultasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambioPlacas;
    private javax.swing.JButton btnModuloConsultas;
    private javax.swing.JButton btnModuloLicencias;
    private javax.swing.JButton btnModuloPlacas;
    private javax.swing.JButton btnModulodeReportes;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
